# Generated by Django 3.0.5 on 2020-04-20 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spuggy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=200)),
                ('issue_description', models.TextField(blank=True)),
                ('issue_image', models.ImageField(blank=True, upload_to='issueimg/')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('issue_status', models.CharField(max_length=50)),
                ('issue_tag', models.CharField(choices=[('UI', 'Enhancement/UI'), ('Bug', 'Bug')], default='Bug', max_length=100)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_handler', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_creator', to=settings.AUTH_USER_MODEL)),
                ('issue_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spuggy.Project_model')),
            ],
        ),
    ]
