# Generated by Django 3.0.5 on 2020-04-20 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spuggy', '0002_issue_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_model',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_handler', to=settings.AUTH_USER_MODEL),
        ),
    ]
