# Generated by Django 3.0.5 on 2020-04-20 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spuggy', '0003_auto_20200420_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spuggy.Project_model')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spuggy.Issue_model')),
                ('comment_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spuggy.Project_model')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
