# Generated by Django 3.0.5 on 2020-04-28 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spuggy', '0008_auto_20200426_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams_model',
            name='team_member',
        ),
        migrations.AddField(
            model_name='teams_model',
            name='team_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
