# Generated by Django 3.0.5 on 2020-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spuggy', '0010_auto_20200429_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_model',
            name='issue_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Open', 'Open'), ('Rejected', 'Rejected'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved')], default='Created', max_length=100),
        ),
    ]
