# Generated by Django 3.0.5 on 2020-04-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spuggy', '0011_auto_20200429_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teams_model',
        ),
    ]
