# Generated by Django 3.0.5 on 2020-05-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spuggy', '0012_delete_teams_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Admin', 'Admin')], default='Normal', max_length=100),
        ),
    ]
