# Generated by Django 3.0.5 on 2020-05-05 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spuggy', '0014_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_model',
            name='team_members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
