# Generated by Django 3.0.5 on 2020-05-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spuggy', '0015_auto_20200505_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_model',
            name='issue_image',
            field=models.ImageField(blank=True, null=True, upload_to='issueimg/'),
        ),
    ]
