# Generated by Django 3.0.5 on 2020-05-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spuggy', '0016_auto_20200511_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
    ]
